### ISSUE TITLE
Time delay to set alarm off

### ISSUE THREAD

**Issue by GPBruins** [daneedk/com.uc.heimdall#1]
Dear Danee,

Would it be possible to select either PIR or doorsensors that don't alarm immediately, thus giving the option to set the alarm off.

Yours,

Guus

**Comment by daneedk** [comment]
Hello Guus,

If I understand you correctly that is exactly what the Delayed Trigger is for which you can select per sensor. 
It’s described in the first post here: https://forum.athom.com/discussion/4514/app-heimdall-let-homey-watch-over-your-home

**Comment by daneedk** [comment]
@GPBruins Does this answer your question, can this issue be closed?

**Comment by gajdur** [comment]
GPBruins, i think you can make this like that: leave the sensor for that unchecked in the app settings, and than make a flow with when "motion alarm on" and Armed, then deactivate alarm.
