### ISSUE TITLE
log is 1 hour off

### ISSUE THREAD

**Issue by laurenssss** [daneedk/com.uc.heimdall#11]
the log time stamp is 1 hour earlier than actual time

eg time is now 13:30
logs in heimdall are showing 12:30

actual time (human time) in Homey is correct, location is set automatically

**Comment by daneedk** [comment]
Yeah, I'm seeing that too! tracked it back in my log, it seems that 1.5.6-rc.11 provides a different time compared to previous versions.
I'll look into it.

**Comment by daneedk** [comment]
This is confirmed by Athom and will be fixed in rc13

**Comment by laurenssss** [comment]
Confirmed, solved indeed
