### ISSUE TITLE
[Request] Add zone to Alarm reason

### ISSUE THREAD

**Issue by Veldkornet** [daneedk/com.uc.heimdall#12]
Would it be possible to add the device zone to the alarm reason tag?

If I have mupltiple sensors with similar names, it’s good to know which of them were triggered. 

Ie, at the moment the tag is:
Device: Reason

Suggestion:
Zone - Device: Reason

**Comment by daneedk** [comment]
In the next version (1.0.5) there will be an additional tag **Zone** available on the **The alarm is activated** flow card:

<img alt="alarmactivated" src="https://user-images.githubusercontent.com/16610696/37054715-e17f759e-217f-11e8-8968-2bc9b7b8dea7.png">

**Comment by daneedk** [comment]
Version 1.0.5 is published.
