### ISSUE TITLE
other sensors / inputs as motion detector or door contacts

### ISSUE THREAD

**Issue by CliffBroeren** [daneedk/com.uc.heimdall#16]
Your app is Amazing but i still mis a feature,

I have outside a Normal Dumb motion detector connected to the S2 contact of an Fibaro dimmer 2
The only thing he does is send a signal to homey, and homey put on all the garden lights.
Is it possible by 'devices'' to make a virtual  motion detector or doorcontact  that can linked with a flow 
to the sensor (Fibaro switches/dimmers, Binary sensor, etc).
So heimdoll  see a sensor that can use with the alarm.

another option maybe  can it  realised in the settings of heimdall 

;)

**Comment by gewoonjerry** [comment]
Just a thought, but you could also use the "Activate alarm" and "Send information to Heimdall" actioncards, with the trigger being your S2 contact, to achieve your goal.

**Comment by daneedk** [comment]
I have no plans to create a virtual sensor that has the alarm_motion or alarm_contact capability.
The suggestion @gewoonjerry proposed is the way to go:
![image](https://user-images.githubusercontent.com/16610696/37569086-b06cb73e-2add-11e8-91b3-b38a58cd0da6.png)
