### ISSUE TITLE
Sensor active at delay start triggercard?

### ISSUE THREAD

**Issue by gewoonjerry** [daneedk/com.uc.heimdall#17]
I love the app! But i have just a minor request:

Is it possible to let Heimdall warn me about active sensors on starting the delay instead of the (partially) activated state?
I'm using the delay to leave the house after i tell homey i'm leaving, because upon (partially) activation Heimdall it locks my frontdoor and besides that it won't bug me with an activated alarm of the frontdoor opening.
The problem of this, is that i can't hear the warning about any sensors.

So an additional triggercard "Sensor active at delay start" or via the settings page, would solve this.

**Comment by daneedk** [comment]
I will look into it, see what I can do without making it confusing.

**Comment by daneedk** [comment]
Settings is included in version 1.0.10:

![image](https://user-images.githubusercontent.com/16610696/37570288-5d34c370-2aee-11e8-8eb7-712186548b2c.png)

In the overview below the first arming action was performed with the setting **Perform Pre-Arming check before Arming Delay** disabled, the second arming action was with the settings enabled:

![image](https://user-images.githubusercontent.com/16610696/37570282-4c936094-2aee-11e8-9fb1-b1166df96e22.png)

(This version will not yet be submitted for approval; Version 1.0.9 is currently pending approval)

**Comment by gewoonjerry** [comment]
Thanks! Bought you a beer!

**Comment by daneedk** [comment]
Thank you very much!
I wish I could tell you when I can submit this version for approval but the previous version (1.0.9) is still waiting for approval by Athom.

**Comment by daneedk** [comment]
Version 1.0.9 is approved by Athom so I've submitted 1.0.10, containing this change, for approval.

**Comment by daneedk** [comment]
Version 1.0.10 containing this change is published.
