### ISSUE TITLE
Add flowcard option to catch log events for a specific zone when heimdall is set to log

### ISSUE THREAD

**Issue by pohomey** [daneedk/com.uc.heimdall#18]
Sometimes you also want to catch log events (not thus not only when armed) to e g trace movement. 
Add flowchart option to catch (log) events for a specific zone (or all). When triggered - consider to provide tags for time (and if all zones is supported - also tag for zone).

**Comment by daneedk** [comment]
@pohomey 
I don't understand what you are asking, can you explain?
What problem are you trying to solve?

**Comment by pohomey** [comment]
Sorry - the title was mangled by apple predictive word replacements/"corrections" (fixed it). See below for more info (please don't hesitate to aske questions). I think helimdall is by far the best tool for security I'v seen outside a real alert system. I was hoping to get it to expand in scope somewhat. 

I'd like a flowcard that catches movement events when heimdall is set only to log the event (I her not seen that kind of card - or have I missed something?). I understand that I can use flowcards to catch alarm events when the system is armed and movement create an alert event, but in this case I'd like the option to catch events that normally only would be logged (as configured). The purpose for this is to trace movements happening before an actual alert, where the movements/event itself is not reason to trigger an alarm. E g when an alert event is detected on motion sensor 5 (MS5), did the person causing that alert come by the MS1, MS2 or trough MS3 or possibly trough MS4 before running into the MS5 (causing an alert event). 
Another way to achieve this might be to add option to retrieve the e g last three logged movements before an alert event is triggered and make it available when an actual alert occurs.

Another subject: Is there a tag/card (or internal functionality) to see when the latest logged event occurred? If so - perhaps add option to automatically arm after e g X hours of no (logged) movements? Or (even better) to get a flowcard event when no logged movements/events has occurred in X hours?

**Comment by daneedk** [comment]
So, a flow card that gets triggered when a log line is written for a sensor, with tags for the device and the state. That should be possible.

For your second question, the log lines (in Heimdall) have a time stamp so I guess that's covered. To let something happen when no logged movements/events have occurred you can use the 'A device hasn't reported in ' trigger card and filter on the name tag 
![image](https://user-images.githubusercontent.com/16610696/39143020-c7ee9452-472c-11e8-91fe-42d9e05e4d2b.png)

**Comment by pohomey** [comment]
Yes, "A logline was written" should do the trick - nice.

**Comment by daneedk** [comment]
App is submitted to the app store.

**Comment by daneedk** [comment]
Version 1.0.13 is published
