### ISSUE TITLE
problem deactivating alarm

### ISSUE THREAD

**Issue by satbopper** [daneedk/com.uc.heimdall#2]
if i arm the surveillance mode and i make an alarm by walking into a room,through the flows i made,the result is that the motion alarm is on,on the motion pir.this will also result in a alarm inside heimdall so that is working.
if i make a flow like : if -- the motion pir alarm is off then deactivate alarm in heimdall,no problem this flow will work but it never deactivates the alarm in heimdall
gr
Ronnie

**Comment by daneedk** [comment]
Hi Ronnie,

Can you post a screenshot of the flow you use to deactivate your alarm?
How do you check that de alarm is not deactivated?
Can you perform the same action and post the relevant log from the history on the settings page?

Thanks,

Danee

**Comment by satbopper** [comment]
problem solved,in heimdall settings it shows activating and deactivating alarms but it does not on the latest telephone app there the alarm keeps on flashing allthough it is allready deactivated
lousy tel app hi

**Comment by daneedk** [comment]
Thanks for reporting back. Ill close the issue.
