### ISSUE TITLE
Heimdall Settings - not saving updates

### ISSUE THREAD

**Issue by fspaan** [daneedk/com.uc.heimdall#20]
Trying to do: Change the Heimdall settings and Save
Steps Taken: Using Homey Desktop App --> Settings --> HeimDall Settings --> Change Trigger Delay from 'undefined' to '30' seconds. Save the changes (receive notifications settings have been changed). Also change checkboxes to 'CHECK'

Expected Result: After returning to the Heimdall settings, find the changed values.

Observed Result: After returning to the Heimdall settings, the Trigger delay value is back to 'undefined', check boxes are 'unchecked'.  Also changes to page: 'Spraak' are not changed.
Changes to the sensors buttons are saved.
When using the flow card 'when trigger delay is activated', this does not work.

![image](https://user-images.githubusercontent.com/40559033/41835167-e7826da6-7856-11e8-8754-7ead7bf162e0.png)

**Comment by daneedk** [comment]
@fspaan Was this a fresh install or did this work before? I'm not sure how you got the undefined, when there are no settings the default value's should be loaded.
Did you try rebooting your Homey? Did you try removing and reinstalling the app?

**Comment by fspaan** [comment]
@daneedk This install has been in my Homey for  approx 2 months. It did not work before either, However, I thought it was an user error. But after building the flows as per your instructions on forum.ahtom.com it confirms the settings are not applied (apart from the sensor triggers). 

The Homey is booted every Sunday by default.  I will try the reinstall.

**Comment by fspaan** [comment]
Just removed and reinstalled... it seems to have helped. I will monitor over the next few days. Thanks.

**Comment by daneedk** [comment]
Great, Think it will be ok from now on.
