### ISSUE TITLE
Vision garagedeur sensor

### ISSUE THREAD

**Issue by MarcelS1988** [daneedk/com.uc.heimdall#24]
Can you add the Garagedeur sensor from Vision?
It is a simple contact alarm or not.
Thank you!

**Comment by daneedk** [comment]
There are no actual devices added to Heimdall. Heimdall goes through all available devices and checks for the alarm_motion, alarm_contact and alarm_tamper capabilities. If any of these capabilities are found the device will be visible on the settings tab.

New devices should show up automatically in the devices overview, on rare occasions it is needed to stop and start the app, could you try that?

How many devices are visible in the devices overview? Some browsers don't show a scroll bar, did you try scrolling the devices overview?

I don't have the actual device we're talking about here so I can't test it myself. To look into it I would require the log that is written when Heimdall is running from the cli.
Can you run the app from the cli and send me the startup log.

Instructions to run an app from the cli can be found here: https://github.com/daneedk/com.uc.heimdall/issues/24

**Comment by MarcelS1988** [comment]
Thank you!
I restart the app and now I see it:)Yesterday with a Motion sensor from fibaro it was automaticly there...
