### ISSUE TITLE
Aeotec zw120

### ISSUE THREAD

**Issue by CaptainStaplerz** [daneedk/com.uc.heimdall#26]
Is it possible to add support for the Aeotec zw120 door/window sensor?
The device is unfortunately not supported by Aeotec atm.

**Comment by daneedk** [comment]
No, I’m sorry, Heimdall can (and will) only support devices with certain capabilities that are exposed by the driver for that particulair device. 
The current Aeotec app does not support this device, the rewrite of the app to sdk2 does support this device, so the wait is for Athom to finish this new version and release it.
