### ISSUE TITLE
Sensors missing and renaming sensors does not affect the settings

### ISSUE THREAD

**Issue by sorenhl** [daneedk/com.uc.heimdall#29]
Hi,

I have a lot of ZigBee door sensors and all of them works.
But when I move one sensor from one room to another room, it does not affect the settings panel.
And it seems like the last sensor I added was not showing up in the settings panel as well.

Is there a way to "reset" the settings without having to uninstall/install, maybe that would help?

**Comment by daneedk** [comment]
Good you found it, that would have been my advise to do. 
Normally changes in names should be picked up automaticaly but there seems something fishy is going on when retrieving the device information from Homey. I filed a bug report at Athom earlier about it and I’ll try to recreate your problem to see if it’s related.
