### ISSUE TITLE
Variable Card   ''Reason'' Adjust: True to Openend/Motion detect

### ISSUE THREAD

**Issue by CliffBroeren** [daneedk/com.uc.heimdall#3]
Would it be possible to use the '' Reason '' Variable.  adjust to (For example) : ''Backdoor Open'' instead of ''Backdoor True'' . And by a Motion sensor     ''Living Motion Detected'' instead of ''Living True'' 

it is not necessarily an issue, but its nicer
Especially for homey talk, He say now Backdoor: True that sounds weird ;-)
and also for Push message it's nicer when you get Openend then True

**Comment by daneedk** [comment]
Good idea. Should be possible so you can expect it in a future version.

**Comment by CliffBroeren** [comment]
Nicee 😊. You’re great  :-)

**Comment by daneedk** [comment]
Version 0.1.2 containing the change submitted for review.

**Comment by daneedk** [comment]
Version 0.1.2 is approved and published.

**Comment by CliffBroeren** [comment]
![img_2303](https://user-images.githubusercontent.com/28061478/35103668-d2d65cbc-fc66-11e7-98e5-857eb0bd7c12.png)
Great Feature, Works like a charm ;)    Thankyou :-)

**Comment by daneedk** [comment]
Great, thanks for reporting back, I'll close the issue.
