### ISSUE TITLE
Pairing with siren

### ISSUE THREAD

**Issue by kapusticka** [daneedk/com.uc.heimdall#30]
Hi guys. Is possible pairing with siren (Coolcam,etc.)? I need activate siren when window open after 5 minutes. And deactivate siren 0 seconds after closing window. Thanks for help.

**Comment by daneedk** [comment]
No, it's not possible to 'pair' a sirene with Heimdall. 
If you just need to activate a sirene when a windows is open for 5 minutes regardless of a Surveillance Mode you're better off creating a flow that is triggered on the opening of the window and switch on the sirene with a delay.
If you want the sirene to only go off in a particular **Surveillance Mode** you will have to set a **Alarm Delay** of 300 seconds and enable the **Delayed Trigger** on the window sensor.
Than use the regular triggercard **The alarm is activated** to turn on the sirene. Make another flow that disable the sirene when the window is closed.
How to configure Heimdall and use the flowcards is described [here](https://community.athom.com/t/heimdall-let-homey-watch-over-your-home/134)
