### ISSUE TITLE
Heimdall keeps resetting alarm after tag is read

### ISSUE THREAD

**Issue by fke1964** [daneedk/com.uc.heimdall#35]
Hoi Danee, het gaat als volgt.
1: tag presenteren , ingang 1 binairi sensor geopend (tijdelijk) Heimdal telt 15 seconden af.
2: gedurende de 15 seconden presenteer ik wederom de tag. Reden is annuleren van het alarm. Heimdal gaat opnieuw 15 seconden aftellen. (tegelijkertijd je hoort dus 2X aftellen door elkaar)
3 als de alarm status naar geactiveerd is (away) en ik presenteerd de tag wordt het alarm netjes uitgezet.
gr,
Frans

**Comment by fke1964** [comment]
![screenshot_20190207-181857](https://user-images.githubusercontent.com/47427695/52431116-dd5aed80-2b07-11e9-8879-71c067fdc282.jpg)
![screenshot_20190207-184141](https://user-images.githubusercontent.com/47427695/52431550-bb159f80-2b08-11e9-90aa-52c39965527d.jpg)
![screenshot_20190207-184325](https://user-images.githubusercontent.com/47427695/52431564-c2d54400-2b08-11e9-99b7-30cd18bf07c8.jpg)
![screenshot_20190207-184344](https://user-images.githubusercontent.com/47427695/52431569-c5d03480-2b08-11e9-9651-28b6ef095cc3.jpg)
![screenshot_20190207-184357](https://user-images.githubusercontent.com/47427695/52431576-c963bb80-2b08-11e9-9b0a-98b388dd15f1.jpg)
![screenshot_20190207-184812](https://user-images.githubusercontent.com/47427695/52431675-fd3ee100-2b08-11e9-9a8d-ca99311b105c.jpg)
![screenshot_20190207-184928](https://user-images.githubusercontent.com/47427695/52431805-3f682280-2b09-11e9-8161-cefd3052d6e4.jpg)
![screenshot_20190207-184941](https://user-images.githubusercontent.com/47427695/52431811-43944000-2b09-11e9-94cf-5d7d1ecc0a8f.jpg)

**Comment by fke1964** [comment]
![screenshot_20190207-190138](https://user-images.githubusercontent.com/47427695/52432546-fb761d00-2b0a-11e9-82d3-0a9cf82764d8.jpg)
![screenshot_20190207-190157](https://user-images.githubusercontent.com/47427695/52432559-ffa23a80-2b0a-11e9-948d-7e55ab688576.jpg)

**Comment by fke1964** [comment]
![screenshot_20190207-195637](https://user-images.githubusercontent.com/47427695/52435892-37ad7b80-2b13-11e9-98d3-bf535902c2b1.jpg)
![screenshot_20190207-195648](https://user-images.githubusercontent.com/47427695/52435900-3aa86c00-2b13-11e9-8d43-3c44cb3c34d4.jpg)
![screenshot_20190207-195811](https://user-images.githubusercontent.com/47427695/52435904-3ed48980-2b13-11e9-97d6-b943414539c6.jpg)
![screenshot_20190207-195927](https://user-images.githubusercontent.com/47427695/52435914-41cf7a00-2b13-11e9-8e5a-dd35319531e8.jpg)
![screenshot_20190207-195941](https://user-images.githubusercontent.com/47427695/52435920-44ca6a80-2b13-11e9-985f-bf0189270685.jpg)
![screenshot_20190207-195950](https://user-images.githubusercontent.com/47427695/52435926-47c55b00-2b13-11e9-953f-62e457349233.jpg)

**Comment by daneedk** [comment]
Hi Frans, 
(Mijn antwoord is in het Engels zodat meer mensen die meelezen het kunnen begrijpen)

I've looked into this, but what is happening makes sense to me:
(Assuming the Surveillance Mode is set to Disarmed to start with)

- When you present the tag the **Surveillance Mode** is checked and returns **Disarmed** so a countdown to set the **Surveillance Mode** is started (the actual Surveillance Mode value is still disarmed, this will change after the countdown timer runs out)
- When you now present the tag while the **Arming Delay** is active the **Surveillance Mode** will still return **Disarmed** which technically is correct but has an undesired effect in your flow. 
To solve this, please add the **Arming countdown active** (Inschakel vertraging actief) condition card and select _Invert_ when adding it so the _And..._ part looks like this:
![image](https://user-images.githubusercontent.com/16610696/52439493-ed7cc800-2b1b-11e9-8cc0-bcbfa8821227.png)
This will make sure the arming only takes place when the **Surveillance Mode** is **Disarmed** and no arming is scheduled.

To make it possible to stop a running **Arming Delay** and set the **Surveillance Mode** to **Disarmed** you have to create an extra flow:

Use the same trigger card from the Universal Sensor:Ingang 1 geopend
In the _And..._ part add the **Surveillance Mode is** (Toezicht Mode is) card and select **Disarmed**. Also add the **Arming countdown active** card so it will look like this:
![image](https://user-images.githubusercontent.com/16610696/52439911-ffab3600-2b1c-11e9-834a-042774e24893.png)
In the **Then...** part you have to add the cards as in the _alarm uitzetten met tag_ flow.

(I suggest you put the actions for disarming in a single flow and use the builtin **This flow is started** card as trigger for that flow. You can now start that flow from any other flow by using the **Start a Flow** action card.)

**Comment by fke1964** [comment]
Hoi Danee,

De fout dat heimdall opnieuw gaat aftellen is er uit. Echter als ik niet de 2e keer te tag presenteerd zegt heimdall (althans een flow) het alarm is uitgezet. Heimdall blijft echter doorgaan met het aftellen en zet het alarm aan


Gr,
Frans

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: daneedk <notifications@github.com>
Verzonden: Thursday, February 7, 2019 9:19:57 PM
Aan: daneedk/com.uc.heimdall
CC: fke1964; Author
Onderwerp: Re: [daneedk/com.uc.heimdall] Heimdall keeps resetting alarm after tag is read (#35)


Hi Frans,
(Mijn antwoord is in het Engels zodat meer mensen die meelezen het kunnen begrijpen)

I've looked into this, but what is happening makes sense to me:
(Assuming the Surveillance Mode is set to Disarmed to start with)

  *   When you present the tag the Surveillance Mode is checked and returns Disarmed so a countdown to set the Surveillance Mode is started (the actual Surveillance Mode value is still disarmed, this will change after the countdown timer runs out)
  *   When you now present the tag while the Arming Delay is active the Surveillance Mode will still return Disarmed which technically is correct but has an undesired effect in your flow.
To solve this, please add the Arming countdown active (Inschakel vertraging actief) condition card and select Invert when adding it so the And... part looks like this:
[image]<https://user-images.githubusercontent.com/16610696/52439493-ed7cc800-2b1b-11e9-8cc0-bcbfa8821227.png>
This will make sure the arming only takes place when the Surveillance Mode is Disarmed and no arming is scheduled.

To make it possible to stop a running Arming Delay and set the Surveillance Mode to Disarmed you have to create an extra flow:

Use the same trigger card from the Universal Sensor:Ingang 1 geopend
In the And... part add the Surveillance Mode is (Toezicht Mode is) card and select Disarmed. Also add the Arming countdown active card so it will look like this:
[image]<https://user-images.githubusercontent.com/16610696/52439911-ffab3600-2b1c-11e9-834a-042774e24893.png>
In the Then... part you have to add the cards as in the alarm uitzetten met tag flow.

(I suggest you put the actions for disarming in a single flow and use the builtin This flow is started card as trigger for that flow. You can now start that flow from any other flow by using the Start a Flow action card.)

**Comment by fke1964** [comment]
works like a charm again 👍
