### ISSUE TITLE
styling issue @ device list

### ISSUE THREAD

**Issue by eelco2k** [daneedk/com.uc.heimdall#36]
In the settings of the Heimdall app under "Configure App" --> "Devices", the icons of a Philio device is centered in stead of aligned left.

This is because the size is not 300px by 300px (square)  but 150px by 300px (rectangle) and in the CSS the styling is: width: auto.  if set to 30px as well it's fixed.

**Comment by daneedk** [comment]
Thanks for reporting. The devices page is under construction at the moment. Most device icons differ in size and aspect ratio, in the new version all will be centered.
