### ISSUE TITLE
multiple partial states

### ISSUE THREAD

**Issue by llentjes** [daneedk/com.uc.heimdall#38]
Would it be possible to have multiple partial states? e.g. : 
partial1: only the outer sensors enabled (in the evening and i am awake)
partial2: when I am asleep
full: when i am gone

**Comment by daneedk** [comment]
This is something I’ve been thinking about for a long time, unfortunately the builtin capability that Heimdall uses allows for only 3 states, Disarmed, Partially Armed and Armed. 
This capability is tied to the Surveillance Mode Switch which displays these options and while I can create my own capability for multiple states there is no way to create a custom UI component to use those states. 
So for now I can say it will not be something that will be in Heimdall, but it is certainly a feature high on my list to implement when the possibility to create a custom UI component is made available by Athom.
