### ISSUE TITLE
Netatmo Welcome/Presence are not vissible in the Heimdall devices page

### ISSUE THREAD

**Issue by rajanlale** [daneedk/com.uc.heimdall#40]

**Comment by daneedk** [comment]
Heimdall is brand/device agnostic, it shows devices based on their capabilities in Homey. If it doesn't show up in the devices list it's most likely because the driver in Homey does not map the devices functionality to any of the supported capabilities. Unfortunately the Netatmo App isn't open source so I can't check it in the apps code.
Please address this at Athom.

**Comment by rajanlale** [comment]
Hi,

Thanks for the email, but I am not a developer and everything is just new for me.
I can loggin to https://dev.netatmo.com<https://dev.netatmo.com/resources/technical/reference/security/getcamerapicture> and see some API documentation (see attachment).
Do you want me to forward this mail to support.athom.com<https://support.athom.com/>?


[image1.png]

Verstuurd vanaf mijn iPhone

Rajan Lale

Op 18 jun. 2019 om 19:56 heeft Danee <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Heimdall is brand/device agnostic, it shows devices based on their capabilities in Homey. If it doesn't show up in the devices list it's most likely because the driver in Homey does not map the devices functionality to any of the supported capabilities. Unfortunately the Netatmo App isn't open source so I can't check it in the apps code.
Please address this at Athom.

**Comment by daneedk** [comment]
It's not about what the Netatmo can do, but what Athom has mapped to Homey capabilities.
What makes you think the device *should* be visible in Heimdall?

**Comment by rajanlale** [comment]
Hi,

I thought eveything security what is vissable in homey is also vissable in Heimdall, or the permission must be granted first...

Verstuurd vanaf mijn iPhone

Op 20 jun. 2019 om 19:11 heeft Danee <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


It's not about what the Netatmo can do, but what Athom has mapped to Homey capabilities.
What makes you think the device should be visible in Heimdall?

**Comment by daneedk** [comment]
All devices that support _alarm_motion_ and/or _alarm_contact_ capabilties are automatically visible in Heimdall. If the Netatmo devices don't expose these capabilties there they can not be shown in Heimdall, thats a limitation of the Netatmo device or app, not Heimdall.
Would you please be so kind to remove your 1 star rating from the app store as this has nothing to do with the Heimdall app.
Thank you.

**Comment by rajanlale** [comment]
Hi,

Thanks for the support so far, I thinkt Athom must solve this problem or I must look for another sollution.
The camera device supports motion detection, face recgonition, unknown face and more.
I still don’t understand why athom or google can work correctly with netamto but heimdall not (mayby the info bellow is too technical for me to understand correctly).

Rajan Lale

Verstuurd vanaf mijn iPhone

Op 21 jun. 2019 om 12:25 heeft Danee <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


All devices that support alarm_motion and/or alarm_contact capabilties are automatically visible in Heimdall. If the Netatmo devices don't expose these capabilties there they can not be shown in Heimdall, thats a limitation of the Netatmo device or app, not Heimdall.
Would you please be so kind to remove your 1 star rating from the app store as this has nothing to do with the Heimdall app.
Thank you.

**Comment by daneedk** [comment]
Yes, you have to address this at Athom. 
While the Netatmo device may support Motion Detection, the Netatmo app by Athom should translate that functionality into a Homey capability. 
There's really nothing I can do about that.

**Comment by malmentm** [comment]
You can create a flor that triggers the alarm if you want

**Comment by rajanlale** [comment]
Hi,

What is an flor?

Verstuurd vanaf mijn iPhone

Op 29 jul. 2019 om 18:17 heeft malmentm <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


You can create a flor that triggers the alarm if you want

**Comment by malmentm** [comment]
Sorry. I ment flow
