### ISSUE TITLE
Additional cards for sensor setup?

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [daneedk/com.uc.heimdall#41]
Feature request:

Add additional then/else and action cards for sensor setup.  So that it is possible to ask Heimdall what the setup of a sensor is: log, partly or full 
And the possibility to set/change a sensor to a specific setting (log, partly, full).

If flow is run for whatever reason and sensor is on log/partly/full, change it to log/partly/full
If flow is run for whatever reason and sensor is setup as not delayed, change it to delayed

The reason for asking is that I can expand and reduce the size of sensors in partly and full. So If there are additional guests in house, change each sensor to full, if there are no regular guests any more, switch back to partly (the we as owners are at home), with full nobody is home).

Optional possibility ask status of one sensor and then set all sensors in a specific zone to log/partly/full. (don't know if that is already possible with <group> )

**Comment by daneedk** [comment]
I have considered this before but decided to not look into it at that time because Athom said they would release Home Security after some improvements to 2.0 were done. That was in the July 2018 Behind the Magic blog but 2.0 wasn’t actualy released until half a year later and the Zigbee, Backup and Restore and Share a Flow are still not here so maybe I shouldn’t really pay attention to Athoms roadmap.
I will have a look at it, not right now because of other things in life that need my attention.

**Comment by MP-ICT-Diensten** [comment]
Thanks for considering!

**Comment by daneedk** [comment]
Hi Marco,

Started working on this, made the cards for adding/removing first, the rest will follow.
[See the post on the community forum](https://community.athom.com/t/heimdall-let-homey-watch-over-your-home/134/596?u=daneedekruyff)

**Comment by MP-ICT-Diensten** [comment]
Much appreciated! Thanks!

**Comment by daneedk** [comment]
Thanks for the donation!

In the next version the cards for the **Logging** will be added, after that for the **Full** and **Partial** **Surveillance Modes**

**Comment by daneedk** [comment]
Version 2.0.22 which enables changing the **Log** settings on devices is published.
[See the community forum](https://community.athom.com/t/heimdall-let-homey-watch-over-your-home/134/621?u=daneedekruyff)

Next up is the changing of the **Full** and **Partial Surveillance Modes**

**Comment by daneedk** [comment]
Version 2.0.23 is published, in this version the cards to add and remove device from the **Partial-** and **Full Surveillance Modes** are added.

[See the community forum](https://community.athom.com/t/heimdall-let-homey-watch-over-your-home/134/629?u=daneedekruyff)
