### ISSUE TITLE
Invalid type error.

### ISSUE THREAD

**Issue by cjvs** [daneedk/com.uc.heimdall#43]
f280943e-7ea7-41df-9c0a-e4479a68cc0b
![Screenshot_20191107-101926](https://user-images.githubusercontent.com/18570823/68377509-ce62a380-014a-11ea-9daf-b303df256f73.jpg)
Goedemorgen,
Krijg bijgaand bericht als ik de surveillance mode aanpas naar ingeschakeld. Opgelost na restart van de Heimdall app, maar wilde je de info geven.

**Comment by daneedk** [comment]
Thanks for reporting, more users reported this to me, for them it was solved by an update of the Homey app that Athom released.
