### ISSUE TITLE
Is it possible to add a time-out on the second activation of the (delayed) trigger?

### ISSUE THREAD

**Issue by daneedk** [daneedk/com.uc.heimdall#5]
[DieterKoblenz asked:](https://forum.athom.com/discussion/comment/66500/#Comment_66500)

Is it possible to add a time-out on the second activation of the (delayed) trigger? I have a motion sensor and door sensor in the same spot which I've added with a delay. When I open the door, both trigger the flowcard and I get the same warning sound played twice.

**Comment by daneedk** [comment]
This is added in version 0.1.6 Beta.

When a Delayed Trigger Countdown is active any subsequent received _alarm_motion:true_ or _alarm_contact:open_ message from a sensor will be ignored.

**Comment by daneedk** [comment]
There seems to be a bug in this new function: https://github.com/daneedk/com.uc.heimdall/issues/8

**Comment by DieterKoblenz** [comment]
Yes, thanks. (And I see you fixed the bug #8)
