### ISSUE TITLE
Feature request: Voice messages for tags

### ISSUE THREAD

**Issue by dannymertens** [daneedk/com.uc.heimdall#51]
Hi,

Small feature request, is it possible to add a option to use a tag, flow option for the voice commands, so that we can use the voice commands in other flows?
The idea is to use for instance the TTS app from Dennie de Groot to send the voice commands to other speakers and not only the internal Homey speaker

![image](https://user-images.githubusercontent.com/46963011/89659295-fa74a600-d8cf-11ea-8e8c-c23625888bef.png)

Thanks in advance!

**Comment by daneedk** [comment]
Hi Danny, we’ve discussed this on the forum a while back, just noticed you created an issue for it. I’m closing it here.
