### ISSUE TITLE
Dashboard crash on load

### ISSUE THREAD

**Issue by glosi** [daneedk/com.uc.heimdall#52]
After updating to Homey 5.0, Heimdall crashes upon load of the Dashboard.

**Comment by daneedk** [comment]
Can you please explain *crashes upon load of the Dashboard*? When an app crashes a crash report should be sent but I haven't received any.

(Did you wait some time after Homey updated the firmware to 5.0, after the update Homey does quite a bit before its fully operational and that can take some time)

**Comment by glosi** [comment]
Hi, and thanks for a fast response. I updated to 5.0 Rc38 a three days ago and tried entering Heimdall yesterday for the first time since then. When I enter the dashboard, I am no longer able to press menu/tabs in Heimdall, and it also seems like the Homeyapp freeze since I have to close it completely to open it again. 

A few seconds later I also get a message that the Homey app does not respond and need to be closed. I have not seen this happen in any other apps before. 

Best regards
Vidar Glosimot

**Comment by daneedk** [comment]
When you open the Homey app after closing it, does it start then?
If so, can you check if the Heimdall app is still operational?

**Comment by glosi** [comment]
Dashboard still freeze upon opening after Homey has been closed. Have tried to restart Homey a few times without an better result.

Heimdall however seems to be running in the background, since it arms the partial protection every night at the time I have set.

**Comment by daneedk** [comment]
Oh, so it's only the Homey app on your phone that crashes. Homey and Heimdall remain operational.
I can't troubleshoot inside the Homey app on your phone, Heimdall's Dashboard is basically a html page. 

Can you try opening Heimdall's dashboard on: https://developer.athom.com/tools/app-settings (might require you to logon and reload that url) and let me know if the Dashboard loads there.

**Comment by glosi** [comment]
Hi again. Developer crashes both Chrome and the Samsung browser when trying on the phone. But when I try the same page in Chrome on the computer, there is no problem. So the problem seems to be an element on the dashboard that makes the web browsers crash on the phone for some reason. I tried on a different android phone as well now. And got the same problem.

**Comment by daneedk** [comment]
Oh wow, you are saying the dashboard crashes your native browser app on your phone, that’s nasty! Didn’t know that it would be possible for a webpage to crash a browser 😳
The page is build from html, css, javascript and the vue.js framework. I can’t imagine it’s any of those components otherwise there should have been more than 1 report. The only thing I can think of, but that’s just a wild guess, that it is a combination of the pages and a particular device on your Homey.
How many devices do you have on your Homey? 
Could you try disabling all apps for devices, reboot your Homey (wait a little) and then open the dashboard and see what happens?

**Comment by daneedk** [comment]
Another thing (also a wild guess) can you delete Heimdalls history? 
Please make a flow with the **Clear Heimdall history** action card and run that flow.

**Comment by glosi** [comment]
Hi again. "Clear Heimdall history" did the job. Dashboard now opens like it should 👍 I have 29 sensors that are detected by Heimdall. Thank you for your patience and good help. Heimdall is a great app :)
