### ISSUE TITLE
Devices not shown on version 5.0.0-rc38

### ISSUE THREAD

**Issue by pkeuter** [daneedk/com.uc.heimdall#53]
Thanks for creating this application! I have installed the app on version 5.0.0-rc38 and followed the instructions on how to set it up. Unfortunately I don't see any devices in the 'devices'-page.

![Screenshot_20201103-195534.jpg](https://user-images.githubusercontent.com/433441/98028844-fabd0880-1e0e-11eb-832c-03f9565000d9.jpg)

I think this potentially has something to do with the new version of Homey but I am not sure what exactly.

The other pages in the settings are working fine by the way.

I tried restarting Homey and reinstalling and restarting the Heimdall app, but without any success.

Am I the only one having this issue or is it more widespread?

**Comment by daneedk** [comment]
This is the first reports I’ve received untill now. Did you give your Homey enough time to settle after the update?
Is there any information on the Dashboard? 
Could you check if all other device apps are started and then restart **Heimdall** and after 10 minutes send a diagnostics report?

**Comment by pkeuter** [comment]
Yes there is information on the dashboard. That looks perfectly fine. It's just the devices page that doesn't show anything.

All apps are started. Here is the diagnostics  id: 58a61a01-65f5-4372-9b44-e26cc876c234

**Comment by glosi** [comment]
I can see the devices, but I get an error message when opening devices. 

The error that pops up when in web browser is:
![Get Device Error](https://user-images.githubusercontent.com/25842894/98083182-3fca5480-1e7a-11eb-9220-ec93de7861f7.png)

**Comment by daneedk** [comment]
> Yes there is information on the dashboard. That looks perfectly fine. It's just the devices page that doesn't show anything.
> 
> All apps are started. Here is the diagnostics id: 58a61a01-65f5-4372-9b44-e26cc876c234

I’ve looked into the report, it looks ok but it seems you have no devices: 

2020-11-04 08:34:35 [log] [Heimdall] init Heimdall 2.0.39        ----------------------
2020-11-04 08:34:35 [log] [Heimdall] Surveillance Mode:          armed
2020-11-04 08:34:35 [log] [Heimdall] Reading settings:           start
2020-11-04 08:34:35 [log] [Heimdall] Reading settings:           done
2020-11-04 08:34:35 [log] [Heimdall] Enumerating devices:        start
2020-11-04 08:34:36 [log] [Heimdall] Found Mode Switch named:    Surveillance
2020-11-04 08:34:36 [log] [Heimdall] Found Alarm Button named:   Alarm
2020-11-04 08:34:36 [log] [Heimdall] Enumerating devices:        done
2020-11-04 08:34:36 [log] [Heimdall] Heimdall ready for action   ----------------------

What devices would you have expected to see there?

**Comment by daneedk** [comment]
> I can see the devices, but I get an error message when opening devices.
> 
> The error that pops up when in web browser is:
> <image removed for readability>

What happens in the app on your phone?
Can you look in your browsers console and see if there is more information on the error?

**Comment by glosi** [comment]
On the phone: 
I get no error on the device page, but one time the browser crashed upon opening the dashboard again like in issue #52. 

On the computer: 
On the device page, together with the error message, I get these errors in the console:
![Console Get Device Error](https://user-images.githubusercontent.com/25842894/98208553-c1cf8180-1f3d-11eb-9133-6b597c76d75b.png)

**Comment by pkeuter** [comment]
> > Yes there is information on the dashboard. That looks perfectly fine. It's just the devices page that doesn't show anything.
> > All apps are started. Here is the diagnostics id: 58a61a01-65f5-4372-9b44-e26cc876c234
> 
> I’ve looked into the report, it looks ok but it seems you have no devices:
> 
> 2020-11-04 08:34:35 [log] [Heimdall] init Heimdall 2.0.39 ----------------------
> 2020-11-04 08:34:35 [log] [Heimdall] Surveillance Mode: armed
> 2020-11-04 08:34:35 [log] [Heimdall] Reading settings: start
> 2020-11-04 08:34:35 [log] [Heimdall] Reading settings: done
> 2020-11-04 08:34:35 [log] [Heimdall] Enumerating devices: start
> 2020-11-04 08:34:36 [log] [Heimdall] Found Mode Switch named: Surveillance
> 2020-11-04 08:34:36 [log] [Heimdall] Found Alarm Button named: Alarm
> 2020-11-04 08:34:36 [log] [Heimdall] Enumerating devices: done
> 2020-11-04 08:34:36 [log] [Heimdall] Heimdall ready for action ----------------------
> 
> What devices would you have expected to see there?

Well I have quite some devices in place. Like a smart implant, some wifi devices, some lights, but maybe the list is filtering for some specific type of device?

**Comment by pkeuter** [comment]
I think I might have found the answer to my "problem": https://github.com/daneedk/com.uc.heimdall/blob/master/settings/settings.js#L332

Sorry for bothering you with this. I am closing the issue. Thanks for your help!
