### ISSUE TITLE
Dashboard loopt vast.

### ISSUE THREAD

**Issue by DefendorNL** [daneedk/com.uc.heimdall#54]
![Screenshot_20201217-192634_Homey](https://user-images.githubusercontent.com/76176684/102527727-d5721a00-409d-11eb-9c93-e6fd36df09c5.jpg)
Hallo,
De app werkte perfect. Heb sinds kort een nieuwe fibaro deur sensor toegevoegd aan het netwerk en sindsdien loopt hij vast in het configuration menu bij het overzicht in het logboek.
Graag hulp.
Onderstaand code is het diagnostic rapport.
4b2c1885-6c9b-4ad3-9642-2797bfa49aec

Alvast dank! Groot fan.

**Comment by DefendorNL** [comment]
Ik ben erachter dat hij alleen bij Android vastloopt, hij doet het op apple wel perfect, dan loopt de app niet vast.

**Comment by daneedk** [comment]
Hi @DefendorNL 
Helaas is dit iets wat in de Homey app voor op de telefoon zit, niet in de ***Heimdall*** op Homey. Ik heb hier eerder 1 melding over gehad (Issue #53), daar was het verholpen door de geschiedenis leeg te maken.
Dit kan je doen door een flow te maken met de actie kaart **Verwijder Heimdall geschiedenis** en deze uit te voeren.

**Comment by DefendorNL** [comment]
Maat, je hebt helemaal gelijk! Geschiedenis gewist nu werkt de app perfect. Wel raar dat dit probleem zich voordoet op Android, kunnen wij hier niet een permanente oplossing voor zoeken? Ben blij dat je hier achter bent, kan ik tenminste verder, waarvoor mijn dank!
