### ISSUE TITLE
Startup test

### ISSUE THREAD

**Issue by eeckelaertyannick** [daneedk/com.uc.heimdall#59]
I can not disable the 2 first cheques in setting where it cheques the sensors upon strat. The always stay on enable.
![image](https://user-images.githubusercontent.com/82699595/148639049-a29ac40c-7d3c-4c06-adc0-813fe34c0221.png)

"Inschakel controle" first 2

**Comment by daneedk** [comment]
Please scroll down to check the speech settings below **Let Homey tell you when** (Laat Homey het je vertellen als). 
You can only disable the **Check motion sensor(s)** (Controleer bewegingssensoren) and **Check door/window sensor(s)** (Controleer deur/raamsensoren) settings when the **a motion sensor is active when arming** (er beweging is bij inschakelen) and **a door or window is open when arming** (een deur/raam open is bij inschakelen) are disabled in the speech settings.

**Comment by eeckelaertyannick** [comment]
Thx!!! Sry 😅

**Comment by daneedk** [comment]
No problem!
