### ISSUE TITLE
Can't add mode button

### ISSUE THREAD

**Issue by svergie2** [daneedk/com.uc.heimdall#61]
Hi!

I've been using heimdall for years, amazing app! This week I've been experiencing issues with the mode button, it doesn't do anything when you press it. This unfortunately breaks some of my flows. I tried to remove the button but when I went to add it back, I get this message that says that no new devices was found and I can't add the button. Please help!

![D9CD0281-E79B-4BC6-9EEA-A55928E3E0B5](https://user-images.githubusercontent.com/6452600/187059785-6d8446af-0e72-468d-b459-46e865dda871.png)
![D775C0A0-3402-4BFF-8735-E18495A867A8](https://user-images.githubusercontent.com/6452600/187059788-a8a56055-a3f4-41e5-9fc5-c06fa485acbd.png)

**Comment by daneedk** [comment]
The Mode Switch can only have one instance, if homey tells you now new device was found it most likely thinks there is already a Mode Switch. As the adding and removing of device is Homey core functionality I’m not sure how to fix it. 

- Have you tried restarting Homey?
- Have you tried using the webapp instead of the mobile app?

As a last resort you could try removing the app and adding it again.

**Comment by svergie2** [comment]
Hello, yes I've rebooted homey and tried the web app but the issue persists. Is my only option really to reinstall the app? I've created a diagnostic report. Thanks!

93d314ce-f5bc-48fd-bdb3-4e1b7784b9b2

**Comment by daneedk** [comment]
I can't really see from the diagnostic report what I'd like to see as there has been some time between the reboot and sending go the report.
Can you please **Enable** the setting _Not for deactivating of sensors_ in ***Heimdalls*** settings. Next stop and start the ***Heimdall*** app and after a minute or 2 send a diagnostics report.

The strange thing is, it seems to me you still have a **Surveillance Mode Switch** on your Homey. Homey itself thinks so as it won't let you add it again plus, in the diagnostics report I see that ***Heimdall*** is partially_armed (a couple of times) through a flowcard, and actually, the flowcard is a card that is provided by the **Surveillance Mode Switch**

Are you sure you removed the **Surveillance Mode Switch** and not the **Alarm Off Button**? (and thus you're now trying to add the wrong device.)

More information can be found here: https://community.homey.app/t/heimdall-let-homey-watch-over-your-home/134#heading--step2

**Comment by svergie2** [comment]
Thank you for your help. The button seems to have magically reappeared for some reason. Google home app hasn't synced the button yet so I'm positive that it wasn't there earlier. Case closed! 😃
