### ISSUE TITLE
SDK3 time and date not ok in config Heimdall

### ISSUE THREAD

**Issue by bakker284** [daneedk/com.uc.heimdall#63]
after updating to SDK3 version time and date in heimdall config says NaN-NaN-NaN

**Comment by daneedk** [comment]
Thanks for reporting!

Can you please copy-paste the starting information from the console here?

**Comment by bakker284** [comment]
starting??

**Comment by bakker284** [comment]
where do i find the log , sorry can't find it

**Comment by daneedk** [comment]
You are running the app from the CLI right?
After *homey app run* the app will be uploaded to your homey and run. It may take some time but the information should be visible in the window.

**Comment by bakker284** [comment]
<img width="654" alt="Naamloos" src="https://user-images.githubusercontent.com/75581603/196268201-bfe51218-1da8-4d5b-9fd6-c503730be449.png">

**Comment by daneedk** [comment]
Ok, thanks. I will look into it!

**Comment by daneedk** [comment]
I made a small change in app.js. Could you download it (or the whole project) and try again?

If that doesn't help I'll change may Homeys language and test myself with dutch, but that will be tomorrow.

**Comment by bakker284** [comment]
its working ok now

**Comment by daneedk** [comment]
Great, thanks for testing and reporting!
