### ISSUE TITLE
Delay a trigger when person is detected

### ISSUE THREAD

**Issue by GeeGee-be** [daneedk/com.uc.heimdall#67]
Hello, after using home assistant I wanted to see if the Homey pro would be a good alternative. It seems it has less features after a few days of trials (dashboard mainly and live camera view of all my camera's in 1 view...), but I like it and will do some more trials.
For my home security in Home assistant I did set some delay (5 sec) on person detection to avoid false alerts. So even it detects a person for 3 sec, it will not trigger my alarm. Sometimes Unifi camera's detect a bird or cat as person shortly. Unifi is looking into this, but that can take a while.
I wanted to do the same in my Homey using Heimdall, but it seems I can't select to only look at person detection. Is it reacting on motion AND person AND vehicles? Or is Heimdall that smart and uses the trigger of Unifi on person detection when available?
And what about delaying a specific camera detection for X sec? How to set this?

I could not figure out yet the function of the alarm button. It doesn't switch off the alarm by itself.

Thx

**Comment by daneedk** [comment]
Hi,

Homey offers no distinct person detection, it will only expose a so called *alarm_motion* capability. How that is triggered depends on the developer of the app for the used device. Heimdall just acts on the *alarm_motion* signal and is not aware on how it was created.
If the developer of the unifi app is able to have the *alarm_motion* only act on human motion for at least 3 seconds it would give you what you desire, but that’s up to the developer of that app.

**Comment by GeeGee-be** [comment]
Hi,
well, when reading camera data in Homey, it is distinguishing vehicle or car when using the smart detection card. So Homey knows. Issue is I can't get Heimdall to know this.
In my home assistant I just put a delay when a person is detected. But I can't see that kind of option here.
![Smart detection Unifi with tags @camera and @smart detection type](https://github.com/daneedk/com.uc.heimdall/assets/76971374/dea84d79-453e-4f79-970a-4e9e514d7ec3)

**Comment by daneedk** [comment]
Ah, the developer already did ‘his part’ in the unify app and I just saw [your post on the forum](https://community.homey.app/t/heimdall-let-homey-watch-over-your-home/134/1401?u=daneedekruyff), let’s continue this there so others can help out too or learn from it

**Comment by GeeGee-be** [comment]
👌
