### ISSUE TITLE
the tags are wrong

### ISSUE THREAD

**Issue by benotje** [daneedk/com.uc.heimdall#7]
![image](https://user-images.githubusercontent.com/25820512/35482774-24a6b7dc-043a-11e8-8aa0-2663cf744250.png)

**Comment by daneedk** [comment]
Hmm Homey creates those tags as I deliberately didn't configured that for the **_Surveillance Mode Switch_**. 
For that use I created the **_Surveillance Mode is_** (Toezicht mode is) condition card.

![image](https://user-images.githubusercontent.com/16610696/35482931-ff446654-043b-11e8-81a7-07e60d455db9.png)

I'll have to see what I can do about that, for now please the **_Surveillance Mode is_** card

**Comment by daneedk** [comment]
To prevent confusion the global tags will no longer be available in a future version, please use the suggested flow cards.
