### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by bosund** [daneedk/com.uc.heimdall#71]
I love Heimdall.

But there is one thing that I miss from my old Zipato, tey called it Cross Zoning.
The purpose of Cross Zoning is to eliminate false alarms, so that 2+ sensors in a specified interval, is required to trigger the alarm.

Settings:
False alarm elimination:
Number of sensors to trigger alarm: (default 2)
Maximum time between triggers: (default 30 seconds)

**Comment by bosund** [comment]
[
](https://community.zipato.com/knowledge-base/article/virtual-alarm-configuration)

Cross Zoning - to avoid false alarms, Zipato allows you to group as many sensors as you want to confirm each other's detection. When some zone included in the cross zoning group detects an alarm event, it won't trigger an alarm. Instead, it will just stay active and wait for some other zone within the same cross zoning group to confirm this event, by detecting the next alarm event within a pre-defined of time

**Comment by daneedk** [comment]
Will not implement nor accept a Pull Request for this, has been discussed on the forum.
